export const MESSAGE_CODE_LOOKUP = {
    CONNECT: 0,
    DISCONNECT: 1,
    DATA: 2,
};

export const MESSAGE_CODES = {
    0: MESSAGE_CODE_LOOKUP.CONNECT,
    1: MESSAGE_CODE_LOOKUP.DISCONNECT,
    2: MESSAGE_CODE_LOOKUP.DATA,
};

export const LEAVE_AREA_CODE_LOOKUP = {
    CONNECTION_LOST: 0,
    ENTERED_NEW_AREA: 1,
};

export const LEAVE_AREA_CODES = {
    0: LEAVE_AREA_CODE_LOOKUP.CONNECTION_LOST,
    1: LEAVE_AREA_CODE_LOOKUP.ENTERED_NEW_AREA,
};

