export const CONNECTOR_REQUEST_CODES = {
    CLIENT_CONNECT: 0,
    CLIENT_DISCONNECT: 1,
    DATA: 2,
};

export const AREA_RESPONSE_CODES  = {
    CONNECT_SUCCESS: 0,
    DISCONNECT_SUCCESS: 1,
};

export const LEAVE_AREA_CODE_LOOKUP = {
    CONNECTION_LOST: 0,
    ENTERED_NEW_AREA: 1,
};
